before:
  hooks:
    - make clean proto vendor
builds:
  - main: ./cmd/miniopera/main.go
    binary: go-miniopera
    ldflags:
      - -linkmode external -extldflags -static -s -w
      - -X main.gitCommit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Tux

  vendor: Fanton Foundation
  homepage: https://fantom.foundation
  maintainer: Samuel Marks <samuel@fantom.foundation>
  description: BFT Consensus platform for distributed applications.
  license: MIT

  formats:
    - deb
    - rpm

  empty_folders:
    - /var/log/go-miniopera

  files:
    "scripts/daemon/go-mini-opera.service": "/lib/systemd/system/go-miniopera.service"

  # scripts:
  #   preinstall: "scripts/preinstall.bash"
